### ISSUE TITLE
About data scaler

### ISSUE THREAD

**Issue by kkIIun** [addb-swstarlab/TADA#3]
Hi, i have a one question. 

Why did you adapt different scaler to X and Y?
Don't you usually apply the same scaler?

Thank you,

**Comment by Kwon-sein** [comment]
Hello,
Thank you for your interest in my code.

As you mentioned, it is generally preferable to use the same scaler for both X and Y. However, in our case, the value ranges for X (config) and Y (metric) are significantly different, which is why we decided to use different scalers for them.

We will also consider adding a cell to our code in the future that allows for checking the value ranges of each dataset.

Thank you for your great question.
